import { Inter } from "next/font/google";
import Script from "next/script";
import Header from "./components/header/page";
import Footer from "./components/footer/page";

import "./components/header/style.css";
import "./components/slider/style.css";

import "./globals.css";
import "./home.css";
import "./components/footer/style.css";
import "bootstrap/dist/css/bootstrap.css";
// import "owl.carousel/dist/assets/owl.carousel.css";
// import "owl.carousel/dist/assets/owl.theme.default.css";

export const metadata = {
  title: "Crypto News",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" />{" "}
      <Script />
      <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      <Script src="https://unpkg.com/aos@next/dist/aos.js"></Script>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
