import { Inter } from "next/font/google";
import Script from "next/script";
import Header from "./components/header/page";
import Footer from "./components/footer/page";
import Head from "next/head";
import CandlestickBackground from "./components/CandlestickBackground";

import "./components/header/style.css";
;
import "./globals.css";
import "./home.css";
import "./components/footer/style.css";
import "bootstrap/dist/css/bootstrap.css";


export const metadata = {
  title: "Crypto News",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        />
      </Head>
      <body>
        <CandlestickBackground />
        <div className="box">
          <div className="wave -one"></div>
          <div className="wave -two"></div>
          <div className="wave -three"></div>
        </div>
        
        {/* Include Bootstrap JS and AOS script */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="https://unpkg.com/aos@next/dist/aos.js"
          strategy="afterInteractive"
        ></Script>
        

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
